user www-data;
worker_processes 1; # for the RTMP stats to work correctly, we can only have 1 worker
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
	worker_connections 768;
	# multi_accept on;
}

http {

	##
	# Basic Settings
	##

	sendfile on;
	tcp_nopush on;
	types_hash_max_size 2048;
	# server_tokens off;

	# server_names_hash_bucket_size 64;
	# server_name_in_redirect off;

	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	##
	# SSL Settings
	##

	ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
	ssl_prefer_server_ciphers on;

	##
	# Logging Settings
	##

	access_log /var/log/nginx/access.log;
	error_log /var/log/nginx/error.log;

	##
	# Gzip Settings
	##

	gzip on;

	# gzip_vary on;
	# gzip_proxied any;
	# gzip_comp_level 6;
	# gzip_buffers 16 8k;
	# gzip_http_version 1.1;
	# gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

	##
	# Virtual Host Configs
	##

	include /etc/nginx/conf.d/*.conf;
	include /etc/nginx/sites-enabled/*;


	server {
		listen 80;
		server_name belabox.local;

		# Serve static assets (CSS, JS, images)
		location / {
			root /opt/belaUI/public;  # <-- set this to where your assets are stored
			index index.html;
			try_files $uri $uri/ /index.html; # optional, if you're doing SPA
		}

		location /ws/ {
			proxy_pass http://127.0.0.1:8080/;  # Replace with your WebSocket server port
			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "Upgrade";
			proxy_set_header Host $host;
			proxy_read_timeout 86400;
		}

		location /data/ {
			alias /mnt/;
			autoindex on;
			autoindex_exact_size on;
			# Optional: shows file sizes in a human-readable format
			autoindex_localtime on;
			# Optional: shows file times in the server's local time

			# Optional: Allow cross-origin requests (useful for accessing VOD files via JavaScript)
			add_header Access-Control-Allow-Origin *;

			# Optional: Force inline content disposition
			add_header Content-Disposition "inline";

			# Optional: Set MIME types for serving video files
			types {
				video/mp4 mp4;
				video/x-flv flv;
				video/webm webm;
			}
		}
	}
}

#mail {
#	# See sample authentication script at:
#	# http://wiki.nginx.org/ImapAuthenticateWithApachePhpScript
#
#	# auth_http localhost/auth.php;
#	# pop3_capabilities "TOP" "USER";
#	# imap_capabilities "IMAP4rev1" "UIDPLUS";
#
#	server {
#		listen     localhost:110;
#		protocol   pop3;
#		proxy      on;
#	}
#
#	server {
#		listen     localhost:143;
#		protocol   imap;
#		proxy      on;
#	}
#}
